## Librerias

In [3]:
try:
    import pandas as pd
except ImportError:
    print("Pandas not installed")
    %pip install pandas --user

try:
    import matplotlib.pyplot as plt
except ImportError:
    print("Matplotlib not installed")
    %pip install matplotlib --user

import ssl

ssl._create_default_https_context = ssl._create_unverified_context

Pandas not installed
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 14.3 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/martinesteso/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 33.4 MB/s eta 0:00:01
Collecting tzdata>=2022.7
  Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
     |████████████████████████████████| 349 kB 49.7 MB/s eta 0:00:01
Collecting numpy>=1.22.4
  Downloading numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 98.8 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.3.3 pytz-2026.2 tzdata-2026.2
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Matplotlib not installed
Collecting matplotlib
  Downloading matplotlib-3.9.4-cp39-cp39-macosx_11_0_arm64.whl (7.8 MB)
     |████████████████████████████████| 7.8 MB 2.3 MB/s eta 0:00:01
Collecting importlib-resources>=3.2.0
  Downloading importlib_resources-6.5.2-py3-none-any.whl (37 kB)
Collecting pillow>=8
  Downloading pillow-11.3.0-cp39-cp39-macosx_11_0_arm64.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 72.0 MB/s eta 0:00:01
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Requirement already satisfied: packaging>=20.0 in /Users/martinesteso/Library/Python/3.9/lib/python/site-packages (from matplotlib) (26.2)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.3.0-cp39-cp39-macosx_11_0_arm64.whl (249 kB)
     |████████████████████████████████| 249 kB 65.8 MB/s eta 0:00:01
Requirement already satisfied: numpy>=1.23 in /Users/martinesteso/Library/Python/3.9/lib/python/site-packages (from matplotlib) (2.0.2)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.60.2-cp39-cp39-macosx_10_9_universal2.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 101.8 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.7 in /Users/martinesteso/Library/Python/3.9/lib/python/site-packages (from matplotlib) (2.9.0.post0)
Collecting pyparsing>=2.3.1
  Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
     |████████████████████████████████| 122 kB 84.9 MB/s eta 0:00:01
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.4.7-cp39-cp39-macosx_11_0_arm64.whl (64 kB)
     |████████████████████████████████| 64 kB 20.0 MB/s eta 0:00:01
Requirement already satisfied: zipp>=3.1.0 in /Users/martinesteso/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib) (1.15.0)
Installing collected packages: pyparsing, pillow, kiwisolver, importlib-resources, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.0 cycler-0.12.1 fonttools-4.60.2 importlib-resources-6.5.2 kiwisolver-1.4.7 matplotlib-3.9.4 pillow-11.3.0 pyparsing-3.3.2
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

## Lectura de datos

- [Dataset Qatar 2022: https://www.kaggle.com/datasets/shrikrishnaparab/fifa-world-cup-2022-qatar-match-data](https://www.kaggle.com/datasets/shrikrishnaparab/fifa-world-cup-2022-qatar-match-data)

In [5]:
archivo = "https://raw.githubusercontent.com/IgnacioPardo/Tecnologias_Exponenciales_2025/refs/heads/main/qatar.csv"

# Leer datos del archivo
mundial : pd.DataFrame = pd.read_csv(archivo)
mundial

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
0,1,Sun,20-Nov-22,17:00,Al Bayt Stadium,Daniele Orsato,Group A,QATAR,ECUADOR,67372,...,0,1,6,5,0,0,52,72,256,279
1,2,Mon,21-Nov-22,14:00,Khalifa International Stadium,Raphael Claus,Group B,ENGLAND,IRAN,45334,...,0,1,8,13,0,0,63,72,139,416
2,3,Mon,21-Nov-22,17:00,Al Thumama Stadium,Wilton Sampaio,Group A,SENEGAL,NETHERLANDS,41721,...,0,0,9,15,0,0,63,73,263,251
3,4,Mon,21-Nov-22,20:00,Ahmed bin Ali Stadium,Abdulrahman Ibrahim Al Jassim,Group B,UNITED STATES,WALES,43418,...,0,1,7,7,0,0,81,72,242,292
4,5,Tue,22-Nov-22,11:00,Lusail Iconic Stadium,Slavko Vincic,Group C,ARGENTINA,SAUDI ARABIA,88012,...,1,0,4,14,0,0,65,80,163,361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,60,Sat,10-Dec-22,20:00,Al Bayt Stadium,Wilton Sampaio,Quarter-final,ENGLAND,FRANCE,68895,...,1,0,9,15,0,0,49,54,193,308
60,61,Tue,13-Dec-22,20:00,Lusail Iconic Stadium,Daniele Orsato,Semi-Final,ARGENTINA,CROATIA,88966,...,1,0,12,10,0,0,85,63,321,260
61,62,Wed,14-Dec-22,20:00,Al Bayt Stadium,Cesar Ramos,Semi-Final,FRANCE,MOROCCO,68294,...,0,0,13,14,0,0,72,47,328,218
62,63,Sat,17-Dec-22,16:00,Khalifa International Stadium,Abdulrahman Ibrahim Al Jassim,Play-off for third place,CROATIA,MOROCCO,44137,...,0,0,7,14,0,0,75,72,288,277
63,64,Sun,18-Dec-22,16:00,Lusail Iconic Stadium,Szymon Marciniak,Final,ARGENTINA,FRANCE,88966,...,1,2,11,21,0,0,87,104,280,409

In [9]:
# Cuantos partidos se jugaron?
# Completar

len(mundial)

64

In [10]:
# Que datos tiene el dataset? (Pista: usar .info(), .describe(), .columns, .head())
# Checkear columnas
# Completar

print(mundial.columns.tolist())
mundial.info()
mundial.describe()
mundial.head()

['match_no', 'day_of_week', 'date', 'hour', 'venue', 'referee', 'group', '1', '2', 'attendance', '1_xg', '2_xg', '1_poss', '2_poss', '1_goals', '2_goals', 'score', '1_attempts', '2_attempts', '1_conceded', '2_conceded', '1_goal_inside_penalty_area', '2_goal_inside_penalty_area', '1_goal_outside_penalty_area', '2_goal_outside_penalty_area', '1_ontarget', '2_ontarget', '1_offtarget', '2_offtarget', '1_attempts_inside_penalty_area', '2_attempts_inside_penalty_area', '1_attempts_outside_penalty_area', '2_attempts_outside_penalty_area', '1_yellow_cards', '2_yellow_cards', '1_red_cards', '2_red_cards', 'faul_against_1', 'faul_against_2', '1_offsides', '2_offsides', '1_passes', '2_passes', '1_passes_compeletd', '2_passes_compeletd', '1_corners', '2_corners', '1_free_kicks', '2_free_kicks', '1_panelties_scored', '2_panelties_scored', '1_goal_prevented', '2_goal_prevented', '1_own_goal', '2_own_goal', '1_forced_turnovers', '2_forced_turnovers', '1_defensive_pressure_applied', '2_defensive_pressure_applied']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 59 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   match_no                         64 non-null     int64
 1   day_of_week                      64 non-null     object
 2   date                             64 non-null     object
 3   hour                             64 non-null     object
 4   venue                            64 non-null     object
 5   referee                          64 non-null     object
 6   group                            64 non-null     object
 7   1                                64 non-null     object
 8   2                                64 non-null     object
 9   attendance                       64 non-null     int64
 10  1_xg                             64 non-null     float64
 11  2_xg                             64 non-null     float64
 12  1_poss                           64 non-null     int64
 13  2_poss                           64 non-null     int64
 14  1_goals                          64 non-null     int64
 15  2_goals                          64 non-null     int64
 16  score                            64 non-null     object
 17  1_attempts                       64 non-null     int64
 18  2_attempts                       64 non-null     int64
 19  1_conceded                       64 non-null     int64
 20  2_conceded                       64 non-null     int64
 21  1_goal_inside_penalty_area       64 non-null     int64
 22  2_goal_inside_penalty_area       64 non-null     int64
 23  1_goal_outside_penalty_area      64 non-null     int64
 24  2_goal_outside_penalty_area      64 non-null     int64
 25  1_ontarget                       64 non-null     int64
 26  2_ontarget                       64 non-null     int64
 27  1_offtarget                      64 non-null     int64
 28  2_offtarget                      64 non-null     int64
 29  1_attempts_inside_penalty_area   64 non-null     int64
 30  2_attempts_inside_penalty_area   64 non-null     int64
 31  1_attempts_outside_penalty_area  64 non-null     int64
 32  2_attempts_outside_penalty_area  64 non-null     int64
 33  1_yellow_cards                   64 non-null     int64
 34  2_yellow_cards                   64 non-null     int64
 35  1_red_cards                      64 non-null     int64
 36  2_red_cards                      64 non-null     int64
 37  faul_against_1                   64 non-null     int64
 38  faul_against_2                   64 non-null     int64
 39  1_offsides                       64 non-null     int64
 40  2_offsides                       64 non-null     int64
 41  1_passes                         64 non-null     int64
 42  2_passes                         64 non-null     int64
 43  1_passes_compeletd               64 non-null     int64
 44  2_passes_compeletd               64 non-null     int64
 45  1_corners                        64 non-null     int64
 46  2_corners                        64 non-null     int64
 47  1_free_kicks                     64 non-null     int64
 48  2_free_kicks                     64 non-null     int64
 49  1_panelties_scored               64 non-null     int64
 50  2_panelties_scored               64 non-null     int64
 51  1_goal_prevented                 64 non-null     int64
 52  2_goal_prevented                 64 non-null     int64
 53  1_own_goal                       64 non-null     int64
 54  2_own_goal                       64 non-null     int64
 55  1_forced_turnovers               64 non-null     int64
 56  2_forced_turnovers               64 non-null     int64
 57  1_defensive_pressure_applied     64 non-null     int64
 58  2_defensive_pressure_applied     64 non-null     int64
dtypes: float64(2), int64(48), object(9)
memory usage: 29.6+ KB

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
0,1,Sun,20-Nov-22,17:00,Al Bayt Stadium,Daniele Orsato,Group A,QATAR,ECUADOR,67372,...,0,1,6,5,0,0,52,72,256,279
1,2,Mon,21-Nov-22,14:00,Khalifa International Stadium,Raphael Claus,Group B,ENGLAND,IRAN,45334,...,0,1,8,13,0,0,63,72,139,416
2,3,Mon,21-Nov-22,17:00,Al Thumama Stadium,Wilton Sampaio,Group A,SENEGAL,NETHERLANDS,41721,...,0,0,9,15,0,0,63,73,263,251
3,4,Mon,21-Nov-22,20:00,Ahmed bin Ali Stadium,Abdulrahman Ibrahim Al Jassim,Group B,UNITED STATES,WALES,43418,...,0,1,7,7,0,0,81,72,242,292
4,5,Tue,22-Nov-22,11:00,Lusail Iconic Stadium,Slavko Vincic,Group C,ARGENTINA,SAUDI ARABIA,88012,...,1,0,4,14,0,0,65,80,163,361

## Analisis

### Primera Parte

In [6]:
# Cuantas selecciones participaron?
# Completar

selecciones = set(mundial["1"]).union(set(mundial["2"]))
len(selecciones)

32

In [7]:
# Cuantas fases tiene el mundial?
# Completar

mundial["group"].unique()

array(['Group A', 'Group B', 'Group C', 'Group D', 'Group F', 'Group E',
       'Group G', 'Group H', 'Round of 16', 'Quarter-final', 'Semi-Final',
       'Play-off for third place', 'Final'], dtype=object)

In [11]:
# Cual fue la "attendance" promedio por partido?
# Completar
mundial["attendance"].mean()

np.float64(53191.4375)

In [13]:
# Cual fue el partido con mas diferencia de goles?
# Completar

mundial["dif_goles"] = abs(mundial["1_goals"] - mundial["2_goals"])
mundial.loc[mundial["dif_goles"].idxmax()]

match_no                                                11
day_of_week                                            Wed
date                                             23-Nov-22
hour                                                 17:00
venue                                   Al Thumama Stadium
referee                            Mohammed Abdulla Hassan
group                                              Group E
1                                                    SPAIN
2                                               COSTA RICA
attendance                                           40013
1_xg                                                   3.5
2_xg                                                   0.0
1_poss                                                  81
2_poss                                                  19
1_goals                                                  7
2_goals                                                  0
score                                                  7,0
1_attempts                                              17
2_attempts                                               0
1_conceded                                               0
2_conceded                                               7
1_goal_inside_penalty_area                               7
2_goal_inside_penalty_area                               0
1_goal_outside_penalty_area                              0
2_goal_outside_penalty_area                              0
1_ontarget                                               7
2_ontarget                                               0
1_offtarget                                              8
2_offtarget                                              0
1_attempts_inside_penalty_area                          12
2_attempts_inside_penalty_area                           0
1_attempts_outside_penalty_area                          5
2_attempts_outside_penalty_area                          0
1_yellow_cards                                           0
2_yellow_cards                                           2
1_red_cards                                              0
2_red_cards                                              0
faul_against_1                                           8
faul_against_2                                          12
1_offsides                                               3
2_offsides                                               7
1_passes                                              1061
2_passes                                               231
1_passes_compeletd                                    1003
2_passes_compeletd                                     170
1_corners                                                5
2_corners                                                0
1_free_kicks                                            18
2_free_kicks                                            11
1_panelties_scored                                       1
2_panelties_scored                                       0
1_goal_prevented                                         0
2_goal_prevented                                        17
1_own_goal                                               0
2_own_goal                                               0
1_forced_turnovers                                      46
2_forced_turnovers                                      76
1_defensive_pressure_applied                           185
2_defensive_pressure_applied                           585
dif_goles                                                7
Name: 10, dtype: object

In [14]:
# Cual es la selección que mas penales metió?
# Completar

penales_local = mundial.groupby("1")["1_panelties_scored"].sum()
penales_visitante = mundial.groupby("2")["2_panelties_scored"].sum()
penales_total = penales_local.add(penales_visitante, fill_value=0)
penales_total.idxmax()

'ARGENTINA'

In [15]:
# Cual es la selección que mas penales le hicieron?
# Completar

penales_contra_local = mundial.groupby("1")["2_panelties_scored"].sum()
penales_contra_visitante = mundial.groupby("2")["1_panelties_scored"].sum()
penales_contra = penales_contra_local.add(penales_contra_visitante, fill_value=0)
penales_contra.idxmax()

'FRANCE'

### Segunda Parte

In [ ]:
equipo : str = "ARGENTINA"

In [ ]:
# Seleccionar todos los partidos que jugo el equipo de "local"
# Completar

filtroLocal : pd.Series =

In [ ]:
# Seleccionar todos los partidos que jugo el equipo de "visitante"
# Completar

filtroVisitante : pd.Series =

In [ ]:
# Seleccionar todos los partidos que jugo el equipo (de "local" o "visitante")
# Completar

partidos : pd.DataFrame =

In [ ]:
# Cuantos goles hizo el equipo en total (obtener los goles metidos de local y sumarlos con los goles metidos de visitante)
# Completar

goles : int =

In [ ]:
# Cuantos goles hizo el equipo en promedio
# Completar

In [ ]:
# Cuantos partidos gano el equipo
# Completar

ganados : int =

In [ ]:
# Graficar los goles hechos por el equipo en cada partido

fig, ax = plt.subplots()
# Completar

### Tercera Parte

In [ ]:
# Contar cuantos goles hizo cada equipo en total en el mundial
# Completar

equipos = 
goles =

In [ ]:
# Graficar los goles por equipo en todo el mundial

fig, ax = plt.subplots()
# Completar

In [ ]:
# Cual es el equipo que hizo mas goles en el mundial?
# Completar

In [ ]:
# Por cada partido, cual fue la diferencia de goles?
# Completar

In [ ]:
# Por cada partido, cual fue el equipo que gano?
# Completar

In [ ]:
# En cada fase del mundial, cual fue el equipo que hizo mas goles?
# Completar

### Tercera Parte

In [ ]:
# Armar un gráfico a partir de algun nuevo análisis que se te ocurra
# Completar